### ISSUE TITLE
Doesn't compile in STM32CubeIDE v1.13.2

### ISSUE THREAD

**Issue by miller-craig** [riverdi/riverdi-eve#11]
In file included from ../Core/Inc/platform.h:30,
                 from ../Core/Src/App_Common.c:35:
../Core/Inc/modules.h:22:4: error: #error "Please choose generation of Embedded Video Engine (EVE_1, EVE_2, EVE_3, EVE_4)"
   22 |   #error "Please choose generation of Embedded Video Engine (EVE_1, EVE_2, EVE_3, EVE_4)"
      |    ^~~~~

**Comment by lukasz-skalski** [comment]
Please make sure that you rename Makefile.stm32 file to Makefile, and started new project in STM32CubeIDE via:
File -> New -> Other -> C/C++ -> Makefile Project with Existing Code.
